import numpy as np
import matplotlib.pyplot as plt
import os
plt.style.use('Solarize_Light2')

# Set the directory containing the files
dir_path = './times'

# Define the list of nodes
nodes = [9, 14, 19, 24, 29, 34, 39, 44, 49]

# Initialize the array to hold the average times
avg_times = np.zeros(len(nodes))

# Loop over the files and compute the average time for each node count
for i, node in enumerate(nodes):
    file_path = os.path.join(dir_path, f"times_{node}_100.txt")
    times = np.loadtxt(file_path)
    avg_times[i] = np.mean(times)

# Plot the average times as a function of the number of nodes
plt.plot(nodes, avg_times, 'o-')
plt.xlabel('Number of nodes')
plt.ylabel('Time (seconds)')
plt.title('Average ACO algorithm running time vs. number of nodes')
plt.grid(True)

# Annotate each point with its corresponding x, y values
for x, y in zip(nodes, avg_times):
    label = f"({x}, {y:.2f})"
    plt.annotate(label, (x, y), textcoords="offset points", xytext=(0,10), ha='center')

# Save the plot to a PDF file
plt.savefig('time_vs_nodes.pdf')

# for future versions this table will be generated by main instead so that we don't have it hardcoded

data = np.array([
    [9, 36, 13],
    [14, 91, 98],
    [19, 95, 104],
    [24, 147, 87],
    [29, 141, 29],
    [34, 168, 89],
    [39, 182, 98],
    [44, 190, 89],
    [49, 171, 87]
])

# Extract the ants and iterations data
ants = data[:,1]
iterations = data[:,2]

# Create the plot of time vs ants
plt.plot(ants, avg_times, 'o-')
plt.xlabel('Number of ants')
plt.ylabel('Time (seconds)')
plt.title('Average ACO algorithm running time vs. number of ants')
plt.grid(True)

# Annotate each point with its corresponding x, y values
for x, y in zip(ants, avg_times):
    label = f"({x}, {y:.2f})"
    plt.annotate(label, (x, y), textcoords="offset points", xytext=(0,10), ha='center')

# Save the plot to a PDF file
plt.savefig('time_vs_ants.pdf')

# Create the plot of time vs iterations
plt.clf()  # Clear the current plot
plt.plot(iterations, avg_times, 'o-')
plt.xlabel('Number of iterations')
plt.ylabel('Time (seconds)')
plt.title('Average ACO algorithm running time vs. number of iterations')
plt.grid(True)

# Annotate each point with its corresponding x, y values
for x, y in zip(iterations, avg_times):
    label = f"({x}, {y:.2f})"
    plt.annotate(label, (x, y), textcoords="offset points", xytext=(0,10), ha='center')

# Save the plot to a PDF file
plt.savefig('time_vs_iterations.pdf')
